name: Build & Deploy to Azure VM

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-iot-app:latest .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-iot-app:latest

      - name: Debug Secrets
        run: |
         echo "USER=${{ secrets.VM_USER }}"
         echo "HOST=${{ secrets.VM_HOST }}"
          

      # âœ… PURE SSH PART STARTS HERE
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on Azure VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-iot-app:latest
            docker stop my-iot-container || true
            docker rm my-iot-container || true
            docker run -d \
              --name my-iot-container \
              -p 8081:8080 \
              -e CONNECTION_STRING='${{ secrets.CONNECTION_STRING }}' \
              ${{ secrets.DOCKER_USERNAME }}/my-iot-app:latest
          EOF